/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import view.CadastroCliente;

/**
 *
 * @author tiago
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButtonCadastro = new javax.swing.JToggleButton();
        jToggleButtonRelatorio = new javax.swing.JToggleButton();
        jToggleButtonAgenda = new javax.swing.JToggleButton();
        jToggleButtonCliente = new javax.swing.JToggleButton();
        LabelFundoMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jToggleButtonCadastro.setText("Cadastro Cliente");
        jToggleButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastroActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(958, 97, 190, 60));

        jToggleButtonRelatorio.setText("Relatorio");
        jToggleButtonRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonRelatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(961, 180, 190, 50));

        jToggleButtonAgenda.setText("Agenda");
        jToggleButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 260, 190, 50));

        jToggleButtonCliente.setText("Cliente");
        jToggleButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButtonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, 190, 50));

        LabelFundoMenuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/fundo-MenuPrincipal.png"))); // NOI18N
        getContentPane().add(LabelFundoMenuPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonClienteActionPerformed

    private void jToggleButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAgendaActionPerformed
       Agenda teladeagenda = new Agenda();
       teladeagenda.setVisible(true);
       
    }//GEN-LAST:event_jToggleButtonAgendaActionPerformed

    private void jToggleButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastroActionPerformed
        CadastroCliente telaDeCadastro = new CadastroCliente();
        telaDeCadastro.setVisible(true);
    }//GEN-LAST:event_jToggleButtonCadastroActionPerformed

    private void jToggleButtonRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelFundoMenuPrincipal;
    private javax.swing.JToggleButton jToggleButtonAgenda;
    private javax.swing.JToggleButton jToggleButtonCadastro;
    private javax.swing.JToggleButton jToggleButtonCliente;
    private javax.swing.JToggleButton jToggleButtonRelatorio;
    // End of variables declaration//GEN-END:variables
}
